config/routes.rb
Startonrails::Application.routes.draw do
  scope '/admin' do
		devise_for :users, :path => 'usuarios', :path_names => {:sign_in => 'login', :sign_out => 'sair', :password => 'senha', :confirmation => 'confirmacao', :unlock => 'desbloquear', :sign_up => 'registrar'}

		resources :posts do
			resources :comments
			
		  collection do
		    put :publish
		    put :moderated
		  end
		end

  end

  get 'post/:id' => 'home#post', as: :home_post

  root :to => 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role.name == "ADMIN"
      can :manage, :all
    elsif user.role.name == "EDITOR"
      can :manage, Post
      can :manage, Comment
    else
      can :read, Post, :published => true
      can :read, Comment, :published => true
    end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :email, :name, :published, :published_at, :status, :post_id
  belongs_to :post
  VALIDATE_EMAIL = /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/

  validates :name, :email, :description, presence: true
  validates :email, format: { with: VALIDATE_EMAIL, on: :create }
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title, :published, :moderated, :user_id
  has_many :comments
  belongs_to :user
  scope :available,  where(published: true)

  validates :title, :description, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :login, :role_id

  belongs_to :role
  has_many :posts

  validates :name, :login, :presence => true
  validates :login, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :json
  layout 'admin'

  def index
  	@comments = Comment.all
 	end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(params[:comment])
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'

      redirect_to root_path
    end
  end		
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	respond_to :html

  def index
   @posts = Post.available
  end

  def post
  	@post = Post.find(params[:id])
  	@comment = @post.comments.build
  	respond_with @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"
  respond_to :html, :json, :js
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)

    respond_with @posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_with @post
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_with @post
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
   end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with @post
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    flash[:notice] = 'Post was successfully updated.' if @post.update_attributes(params[:post])
    respond_with @post
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_with @post
  end

  def publish
    @post = Post.find(params[:id])
    @post.published = (@post.published) ? false : true
    @post.save
    respond_with @post
  end

  def moderated
    @post = Post.find(params[:id])
    @post.moderated = (@post.moderated) ? false : true
    @post.save
    respond_with @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def outgoing_menssage
    if notice
      raw "<h4 class='alert_success'>#{notice}</h4>"
    end
  end

  def arrow_left
    image_tag('icons/116767-matte-blue-and-white-square-icon-arrows-arrow-thick-left.png', height: '50px', width: '50px')
  end

  def arrow_right
    image_tag('icons/116768-matte-blue-and-white-square-icon-arrows-arrow-thick-right.png', height: '50px', width: '50px')
  end

  def submit_link(form)
    if params[:action] == 'new'
      form.submit(I18n.t(:create), class: 'btn btn-success')
    else
      form.submit(I18n.t(:update), class: 'btn btn-primary')
    end
  end

  def show_icon(object)
    val = (object) ? true : false
    image_tag "#{val}.png"
  end

  def comments(post)
    html = ""
    post.comments.each do |comment|
      html << "<p>#{comment.name}</p>"
      html << "<p>#{comment.email}</p>"
      html << "<p>#{comment.description}</p>"
    end
    raw html
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="comment well">
  <h3><%= t(:add_comment)%></h3>
  <%= form_for([@post, @comment]) do |f| %>
    <p><%= f.label t(:name)%></p>
    <p><%= f.text_field :name%></p>

    <p><%= f.label t(:email) %></p>
    <p><%= f.text_field :email %></p>

    <p><%= f.label t(:description)%></p>
    <p><%= f.text_area :description %> </p>

    <p><%= f.submit %></p>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_comments %></h2>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= t :name %></th>
    <th><%= t :email %></th>
    <th><%= t :description %></th>
    <!--<th><%#= t :published  %></th>-->		
    <th><%= t :status %></th>
  </tr>
<% @comments.each do |comment| %>
	<tr>
		<td><%= comment.name%></td>
		<td><%= comment.description %></td>
		<td><%= comment.email%></td>
		<!--<td id="comment_publish_<%#= comment.id %>"> <%#= link_to_function show_icon(comment.published), "active(#{comment.id}, '/publish');" %></td>-->
    	<td><%= comment.status%></td>							
    </tr>
	<% end 	%>		
	</table>

app/views/home/index.html.erb
<h1>Start On Rails</h1>
  <div class="posts container">
    <% @posts.each do |post| %>
      <div class="row"> 
        <div class="post span4">
          <h3><%= link_to post.title, home_post_path(post.id) %> </h3>
          <p><%= post.description %> </p>
        </div>
      </div>
    <% end %>
</div>

app/views/home/post.html.erb
<div class="row"> 
	<div class="post span4">
	  <h3><%= @post.title %> </h3>
	  <p><%= @post.description %> </p>
	</div>
</div>
<div class="comments well">
  <%= comments(@post) %> 
</div>
<%= render "comments/form", post: @post %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Description">
    <meta name="keywords" content="Keywords">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag "html5.js" %>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap.css", "bootstrap-responsive.css", "docs.css" %>
    <%= csrf_meta_tags %>

  </head>

  <body class="preview" data-spy="scroll" data-target=".subnav" data-offset="50">
    <!-- Navbar
      ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <% unless current_user.nil? %>
            <div class="brand-right"><%= current_user.email %> <%= link_to I18n.t(:logout), destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <!-- Masthead
      ================================================== -->
      <header class="jumbotron subhead" id="overview">
        <div class="subnav">
          <ul class="nav nav-pills">
            <li><%= link_to t(:home), root_path %></li>
            <li><%= link_to t(:posts), posts_path %></li>
            <li><%= link_to t(:comments), comments_path %></li>
              </ul>
        </div>
      </header>

      <%= yield %>

      <!-- Le javascript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <%= javascript_include_tag "jquery-1.7.2.min.js", "bootstrap.min.js", "app.js", "bootswatch.js" %>

      <!-- Footer
      ================================================== -->
      <footer class="footer">
        <center><p>Footer</p></center>
      </footer>

    </div><!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <title>Startonrails</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="preview">
    <div class="container">
      <p class="notice alert-info"><%= notice %></p>
      <p class="alert alert-error"><%= alert %></p>
      <div id="user_nav" class="nav-bar">
      <% if user_signed_in? %>
        Logado como <%= current_user.email %>. Não é você?
        <%= link_to 'Sair', destroy_user_session_path, :method => :delete %>
        </br>
        <%= link_to 'Post', posts_path %>
      <% else %>
        <%= link_to 'Registrar', new_user_registration_path %> ou <%= link_to 'Logar', new_user_session_path %>
      <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
  </html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:title) %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label t(:description) %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label t(:published) %><br />
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label t(:moderated) %><br />
    <%= f.check_box :moderated %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<script type ='text/javascript'>
function active(id, path){
  $.ajax({
    url: '/posts' + path,
    type: 'put',
    data: {id: id},
    dataType: 'script',
    headers: { 'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'}
  });
}
</script>

app/views/posts/edit.html.erb
<h1><%= t :editing_posts %></h1>

<%= render 'form' %>

<%= link_to t(:show), @post %> |
<%= link_to t(:back), posts_path %>

app/views/posts/index.html.erb
<%= render partial: 'posts' %>
<div class="page-header">
  <h2><%= I18n.t :listing_posts %> - <%= link_to I18n.t(:new_post), new_post_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= t :title %></th>
    <th><%= t :description %></th>
    <th><%= t :published  %></th>
    <th><%= t :moderated %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.description %></td>
    <td id="post_publish_<%= post.id %>"><%= link_to_function show_icon(post.published), "active(#{post.id}, '/publish');" %></td>
    <td id="post_moderated_<%= post.id%>"><%= link_to_function show_icon(post.moderated), "active(#{post.id}, '/moderated');" %></td>
    <td><%= link_to t(:show), post, class: 'btn'  %></td>
    <td><%= link_to t(:edit), edit_post_path(   post), class: 'btn btn-primary' %></td>
    <td><%= link_to t(:destroy), post_path(post.id), :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @posts, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to t(:new_post), new_post_path, class: 'btn btn-success' %>

app/views/posts/moderated.js.erb
<% path = '\"/moderated\"' %>
$("#post_moderated_<%= @post.id%>").empty();
$("#post_moderated_<%= @post.id%>").append('<%= link_to_function show_icon(@post.moderated), "active(#{@post.id}, #{path});"%>');

app/views/posts/new.html.erb
<div class="page-header">
  <h2><%= t :new_post %></h2>
</div>

<%= render 'form' %>

<%= link_to t(:back), posts_path %>

app/views/posts/publish.js.erb
<% path = '\"/publish\"' %>
$("#post_publish_<%= @post.id %>").empty();
$("#post_publish_<%= @post.id %>").append('<%= link_to_function show_icon(@post.published), "active(#{@post.id}, #{path});" %>');

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t :title %></b>
  <%= @post.title %>
</p>

<p>
<b><%= t :description %></b>
  <%= @post.description %>
</p>

<p>
<b><%= t :published %></b>
  <%= @post.published %>
</p>

<p>
<b><%= t :moderated %></b>
  <%= @post.moderated %>
</p>

<%= link_to t(:edit), edit_post_path(@post) %> |
<%= link_to t(:back), posts_path %>